[package]
name = "pseudovalidator"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
log = "0.4"
env_logger = "0.10"
ed25519-dalek = { version = "1", features = ["serde"] }
hex = "0.4"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
soroban-sdk = "0.7"  # Soroban SDK for Stellar smart contracts

[dev-dependencies]
cargo-tarpaulin = "0.26"
mockall = "0.11"

[features]
default = []

[[bin]]
name = "pseudovalidator"
path = "src/main.rs"
