name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust project
        run: |
          cd pseudovalidator
          cargo build --release

      - name: Run Rust tests
        run: |
          cd pseudovalidator
          cargo test

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          cd condition_verifier
          pip install -r requirements.txt

      - name: Run Python tests
        run: |
          cd condition_verifier
          pytest

      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d

      - name: Verify services are running
        run: |
          sleep 5
          curl -X POST http://localhost:5000/verify -F "file=@sample_input_file"
